---
- name: Iptables configuration
  hosts: all
  become: yes
  tasks:
  - name: Disable the firewalld service
    service:
      name: firewalld
      state: stopped
      enabled: false
  tasks:
  - name: "Install iptables-services"
    yum: >
      name=iptables-services
      state=present
    when: ansible_distribution_major_version|int == 7
    tags:
      - firewall
      - pkgs
  tasks: 
  - name: "Enable iptables"
    service: >
      name=iptables
      enabled=yes
      state=started
    when: ansible_distribution_major_version|int == 7
    tags:
      - firewall
  tasks:
  - name: "Install ip6tables rules"
    template: >
      src=ip6tables.j2
      dest=/etc/sysconfig/ip6tables
      owner=root
      group=root
      mode=0600
    register: ip6tables_template
    tags:
      - firewall
      - files
  tasks:
  - name: "Reload ip6tables rules"
    shell: |
      [ -e /sbin/ip6tables-restore ] && /sbin/ip6tables-restore < /etc/sysconfig/ip6tables
    when: ip6tables_template|changed
    tags:
      - firewall