---
- name: User Add
  hosts: all
  become: yes
  vars:
    users:
    - username: "rjb918"
    - username: "barryc"
    - username: "jjn613"
    tasks:

    - name: Add the users to the group wheel 
      group:
        name: wheel
      shell: /bin/bash
      append: yes

    - name: Adding User "{{ item.username }}"
      user:
        name: "{{ item.username }}"