---
- name: User Add
  hosts: all
  become: yes
  tasks:
  - name: Add the users to the group wheel 
    user:
      name: "{{ username }}"
      shell: /bin/bash
      groups: wheel
      append: yes