---
- name: Disable the firewalld service
  become: yes 
  service:
    name: firewalld
    state: stopped
    enabled: false
- name: "Install iptables-services"
  become: yes
  yum:
    name: iptables-services
    state: latest
- name: "Enable iptables"
  become: yes
  service:
    name: iptables
    enabled: yes
    state: started
- name: "Copy iptables rules"
  become: yes
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0600
- name: "Restart iptables"
  become: yes
  service:
    name: iptables
    state: restarted