---
- name: Copy bootstrap script to register new host into Satellite5
  become: yes
  template: 
    src: pim-bootstrap.sh.j2
    dest: /root/pim-bootstrap.sh
    owner: root
    mode: 0755
    
- name: Execute the script
  become: yes
  command: sh /root/pim-bootstrap.sh