---
- name: Iptables configuration
  hosts: all
  become: yes
  tasks:
  - name: Disable the firewalld service
    service:
      name: firewalld
      state: stopped
      enabled: false
  
  tasks:
  - name: "Install iptables-services"
    yum: >
      name=iptables-services
      state=present
    when: ansible_distribution_major_version|int == 7
    tags:
      - firewall
      - pkgs
