---
- name: Disable firewalld and install Iptables
  hosts: all
  become: yes
  tasks:
  - name: Disable firewalld
    command: systemctl disable firewalld
  - name: Stop firewalld
    command: systemctl stop firewalld
  tasks: 
  - name: Install iptables
    yum:
      name: iptables-service
      state: present
  tasks:
  - name: Start iptables
    service:
      name: iptables
      state: started
  tasks:
  - name: Start ip6tables
    service:
      name: ip6tables
      state: started
  tasks:
  - name:  Enable iptables
    service:
      name: iptables
      enabled: yes
  tasks:
  - name: Enable ip6tables
    service:
      name: ip6tables
      enabled: yes
  tasks:
  - name: Allow DAPS VPN SSH Access
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      source: 10.120.47.0/24
      ctstate: NEW
      jump: ACCEPT
      comment:  DAPS Global Protect VPN SSH Access
  tasks: 
  - name: Allow PIPS-Infra VPN SSH Access
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      source: 10.120.46.0/24
      jump: ACCEPT
      comment:  PIPS-OS Global Protect VPN SSH Access
  tasks: 
  - name: Allow MMS Tools Access
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      source: 129.105.106.0/25
      jump: ACCEPT
      comment: Allow MMS Tools Access
  tasks: 
  - name: Restart iptables
    service: 
      name: iptables
      state: restarted
    