---
- name: User Add
  become: yes
  include_vars: "{{ item }}"

- name: Adding User "{{ item.username }}"
  become: yes
  user:
    name: "{{ item.username }}"
    create_home: yes
    groups: wheel
  with_items: "{{ users }}"