---
- name: User Add
  become: yes
  include_vars: appgroup.yaml

- name: Adding User
  become: yes
  user:
    name: "{{ item.name }}"
    create_home: yes
    groups: wheel
  with_items: "{{ users }}"
