---
- name: User Add
  become: yes
  include_vars: DAPS.yaml

- name: Adding User "{{ username }}"
  become: yes
  user:
    name: "{{ username }}"
    create_home: yes
    groups: wheel
  with_items: "{{ users }}"